services:
  - type: web
    name: ancient-war-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        value: 8588773170
      - key: CHANNEL_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ancient_war_db
          property: connectionString
      - key: WEBHOOK_URL
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: ancient_war_db
    databaseName: ancient_war
    user: ancient_war_user
    plan: free
